In [1]:
import os
import re
import json
import math
import time
import torch
import numpy as np
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel
from groq import Groq
from pathlib import Path
from dotenv import load_dotenv


import pandas as pd
from pprint import pprint

from langchain_community.document_loaders import PyPDFLoader

d:\AIT_NLP\NLP\A6_RAG_Techniques\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Task 1: Source Discovery & Data Preparation

Assigned chapter: Chapter 8  
Topic: Transformers

In [39]:
pdf_path = "D:\\AIT_NLP\\nlp\\A6_RAG_Techniques\\Chapter-8 RAG assignment.pdf"

loader = PyPDFLoader(pdf_path)
pages = loader.load()

print("Number of pages:", len(pages))
print("\nFirst 1000 characters from page 1:\n")
print(pages[0].page_content[:1000])

Number of pages: 27

First 1000 characters from page 1:

Speech and Language Processing. Daniel Jurafsky & James H. Martin. Copyright © 2026. All
rights reserved. Draft of January 6, 2026.
CHAPTER
8
Transformers
“The true art of memory is the art of attention ”
Samuel Johnson, Idler #74, September 1759
In this chapter we introduce thetransformer, the standard architecture for build-
ing large language models. As we discussed in the prior chapter, transformer-based
large language models have completely changed the ﬁeld of speech and language
processing. Indeed, every subsequent chapter in this textbook will make use of them.
As with the previous chapter, we’ll focus for this chapter on the use of transformers
to model left-to-right (sometimes called causal or autoregressive) language model-
ing, in which we are given a sequence of input tokens and predict output tokens one
by one by conditioning on the prior context.
Layer Norm
+
Layer Norm
MultiHead
Attention
Feedforward
Softmax
Positional
Unembedding
Embedding
+
residual
stream
N times
outp

Combining All the texts

In [40]:
full_text = "\n".join([page.page_content for page in pages])

print("Total characters:", len(full_text))
print(full_text[:1500])

Total characters: 76773
Speech and Language Processing. Daniel Jurafsky & James H. Martin. Copyright © 2026. All
rights reserved. Draft of January 6, 2026.
CHAPTER
8
Transformers
“The true art of memory is the art of attention ”
Samuel Johnson, Idler #74, September 1759
In this chapter we introduce thetransformer, the standard architecture for build-
ing large language models. As we discussed in the prior chapter, transformer-based
large language models have completely changed the ﬁeld of speech and language
processing. Indeed, every subsequent chapter in this textbook will make use of them.
As with the previous chapter, we’ll focus for this chapter on the use of transformers
to model left-to-right (sometimes called causal or autoregressive) language model-
ing, in which we are given a sequence of input tokens and predict output tokens one
by one by conditioning on the prior context.
Layer Norm
+
Layer Norm
MultiHead
Attention
Feedforward
Softmax
Positional
Unembedding
Embedding
+
residual
stream
N times
output probabilities (over tokens)
+
input token
Layer Norm
+
Layer Norm
MultiHead
Attention
Feedforward
residual
stream
N times
+
Figure 8.1 A transformer decoder for language modeling, showing the residual stream for
processing an input token. A single token is embedded and passed forward in the network,
with the feedforward and attention components adding information. The multihead attention
layer takes inputs (not shown in detail) from the neighboring token streams. This is thus one
column of an

Cleaning text

In [41]:
def clean_text(text: str) -> str:
    text = text.replace("\x00", " ")
    text = text.replace("\t", " ")
    text = re.sub(r" +", " ", text)
    text = re.sub(r"\n{2,}", "\n\n", text)
    return text.strip()

cleaned_text = clean_text(full_text)

print("Cleaned text length:", len(cleaned_text))
print(cleaned_text[:1500])

Cleaned text length: 76763
Speech and Language Processing. Daniel Jurafsky & James H. Martin. Copyright © 2026. All
rights reserved. Draft of January 6, 2026.
CHAPTER
8
Transformers
“The true art of memory is the art of attention ”
Samuel Johnson, Idler #74, September 1759
In this chapter we introduce thetransformer, the standard architecture for build-
ing large language models. As we discussed in the prior chapter, transformer-based
large language models have completely changed the ﬁeld of speech and language
processing. Indeed, every subsequent chapter in this textbook will make use of them.
As with the previous chapter, we’ll focus for this chapter on the use of transformers
to model left-to-right (sometimes called causal or autoregressive) language model-
ing, in which we are given a sequence of input tokens and predict output tokens one
by one by conditioning on the prior context.
Layer Norm
+
Layer Norm
MultiHead
Attention
Feedforward
Softmax
Positional
Unembedding
Embedding
+
residual
stream
N times
output probabilities (over tokens)
+
input token
Layer Norm
+
Layer Norm
MultiHead
Attention
Feedforward
residual
stream
N times
+
Figure 8.1 A transformer decoder for language modeling, showing the residual stream for
processing an input token. A single token is embedded and passed forward in the network,
with the feedforward and attention components adding information. The multihead attention
layer takes inputs (not shown in detail) from the neighboring token streams. This is thus one
column of an

Saving Cleaned Text

In [ ]:
output_dir = Path("answer")
output_dir.mkdir(exist_ok=True)

with open(output_dir / "chapter8_cleaned.txt", "w", encoding="utf-8") as f:
    f.write(cleaned_text)

print("Saved cleaned text to", output_dir / "chapter8_cleaned.txt")

Saved cleaned text to data\chapter8_cleaned.txt

In [43]:
qa_pairs = [
    {
        "question": "What is the primary purpose of the self-attention mechanism in a transformer?",
        "ground_truth_answer": "Self-attention allows a model to build contextual representations of a token by integrating information from other tokens in the sequence.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "In the attention mechanism, what roles do the query, key, and value vectors play?",
        "ground_truth_answer": "The query represents the current token being compared, the key represents tokens used for similarity comparison, and the value contains the information that is weighted and combined in the output.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "Why is a scaling factor used in the dot product of query and key vectors?",
        "ground_truth_answer": "The dot product is scaled by the square root of the key dimension to prevent large values that could cause unstable gradients during training.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "Why do transformers use multi-head attention instead of a single attention head?",
        "ground_truth_answer": "Multi-head attention allows the model to attend to different types of relationships in the sequence simultaneously using multiple attention heads.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What components are included in a standard transformer block?",
        "ground_truth_answer": "A transformer block includes a multi-head self-attention layer, a feedforward network, residual connections, and layer normalization.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },

    {
        "question": "What is the residual stream in a transformer block?",
        "ground_truth_answer": "The residual stream is the pathway where token representations are passed through layers while each component reads from and adds its output back to the stream.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "How are positional embeddings combined with token embeddings in a transformer?",
        "ground_truth_answer": "Positional embeddings are added to token embeddings so the model can represent both the token identity and its position in the sequence.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is the architecture of the feedforward layer in a transformer block?",
        "ground_truth_answer": "The feedforward layer is a two-layer fully connected network applied independently to each token representation.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is the purpose of layer normalization in transformers?",
        "ground_truth_answer": "Layer normalization stabilizes training by normalizing activations so they have a consistent scale across the network.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "Why is masking used in the self-attention of causal language models?",
        "ground_truth_answer": "Masking prevents tokens from attending to future tokens so the model only uses previous context when predicting the next token.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What components make up the language modeling head?",
        "ground_truth_answer": "The language modeling head consists of a linear projection called the unembedding layer followed by a softmax to produce probabilities over the vocabulary.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is weight tying in transformer language models?",
        "ground_truth_answer": "Weight tying refers to sharing the same weight matrix between the token embedding layer and the final unembedding layer.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "How does top-k sampling work during text generation?",
        "ground_truth_answer": "Top-k sampling restricts the probability distribution to the k most likely tokens and randomly samples the next token from that subset.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is the intuition behind top-p or nucleus sampling?",
        "ground_truth_answer": "Top-p sampling selects the smallest set of tokens whose cumulative probability exceeds a threshold p and samples from that set.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What training objective is commonly used for large language models?",
        "ground_truth_answer": "Large language models are typically trained using cross-entropy loss to maximize the probability of the correct next token.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "How does the KV cache improve inference efficiency?",
        "ground_truth_answer": "The KV cache stores key and value vectors from previous tokens so they do not need to be recomputed during autoregressive generation.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "Why is attention sometimes called a token-mixing component?",
        "ground_truth_answer": "Attention is called token-mixing because it integrates information from other tokens into the representation of the current token.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is a decoder-only transformer model?",
        "ground_truth_answer": "A decoder-only transformer is a unidirectional model that predicts tokens autoregressively using only the decoder architecture.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is a limitation of absolute positional embeddings?",
        "ground_truth_answer": "Absolute positional embeddings may generalize poorly to positions near the maximum sequence length because those positions appear less frequently in training.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    },
    {
        "question": "What is the purpose of the logit lens tool?",
        "ground_truth_answer": "The logit lens is an interpretability method that applies the final unembedding layer to intermediate activations to analyze what the model is predicting at different layers.",
        "naive_rag_answer": "",
        "contextual_retrieval_answer": ""
    }
]

In [44]:
with open(output_dir / "qa_pairs.json", "w", encoding="utf-8") as f:
    json.dump(qa_pairs, f, indent=2, ensure_ascii=False)

print("Saved QA pairs to", output_dir / "qa_pairs_task1.json")

Saved QA pairs to data\qa_pairs_task1.json

chunking

In [45]:
def chunk_text(text, chunk_size=500, overlap=50):
    chunks = []
    start = 0
    
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap
    
    return chunks

chunks = chunk_text(cleaned_text, chunk_size=500, overlap=50)

print("Number of chunks:", len(chunks))
print("\nFirst chunk:\n")
print(chunks[0][:800])

Number of chunks: 171

First chunk:

Speech and Language Processing. Daniel Jurafsky & James H. Martin. Copyright © 2026. All
rights reserved. Draft of January 6, 2026.
CHAPTER
8
Transformers
“The true art of memory is the art of attention ”
Samuel Johnson, Idler #74, September 1759
In this chapter we introduce thetransformer, the standard architecture for build-
ing large language models. As we discussed in the prior chapter, transformer-based
large language models have completely changed the ﬁeld of speech and language
processing

embedding model

In [46]:
embedding_model_name = "BAAI/bge-small-en-v1.5"

embed_tokenizer = AutoTokenizer.from_pretrained(embedding_model_name)
embed_model = AutoModel.from_pretrained(embedding_model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
embed_model = embed_model.to(device)
embed_model.eval()

print("Embedding model loaded on:", device)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6627.81it/s]
BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding model loaded on: cpu

In [47]:
def get_embedding(text):
    inputs = embed_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}
    
    with torch.no_grad():
        outputs = embed_model(**inputs)
    
    # CLS token embedding
    embedding = outputs.last_hidden_state[:, 0, :].squeeze().cpu().numpy()
    return embedding

In [48]:
VECTOR_DB = []

for chunk in tqdm(chunks, desc="Embedding chunks"):
    emb = get_embedding(chunk)
    VECTOR_DB.append((chunk, emb))

print("Vector DB size:", len(VECTOR_DB))
print("Embedding dimension:", VECTOR_DB[0][1].shape)

Embedding chunks: 100%|██████████| 171/171 [00:08<00:00, 20.26it/s]

Vector DB size: 171
Embedding dimension: (384,)

cosine similarity + retrieval

In [49]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def retrieve(query, vector_db, top_k=3):
    query_emb = get_embedding(query)
    
    scored_chunks = []
    for chunk, emb in vector_db:
        score = cosine_similarity(query_emb, emb)
        scored_chunks.append((chunk, score))
    
    scored_chunks = sorted(scored_chunks, key=lambda x: x[1], reverse=True)
    return scored_chunks[:top_k]

test retrieval

In [50]:
test_question = "What is self-attention in a transformer?"
retrieved = retrieve(test_question, VECTOR_DB, top_k=3)

print("Question:", test_question)
print()

for i, (chunk, score) in enumerate(retrieved, 1):
    print(f"--- Retrieved chunk {i} | score={score:.4f} ---")
    print(chunk[:1000])
    print()

Question: What is self-attention in a transformer?

--- Retrieved chunk 1 | score=0.8002 ---
ding and all the outputs from all
the previous layers and blocks.
The core intuition of the transformer, and the component that distinguishes it
from the feedforward layers we saw in Chapter 6, is this multi-head attention layer,
also called a self-attention layer. Attention can be thought of as a way to build
contextual representations of a token’s meaning by attending to and integrating
information from surrounding tokens, helping the model learn how tokens relate to
each other over large span

--- Retrieved chunk 2 | score=0.7966 ---
ther linear projection WO∈ RAdv×d to reshape it, resulting in the multi-head
attention vector ai with the correct output shape [1× d] at each input i.
8.2 Transformer Blocks
The self-attention calculation lies at the core of what’s called a transformer block,
which, in addition to the self-attention layer, includes three other kinds of layers: (1)
a feedforward layer, (2) residual connections, and (3) normalizing layers (colloqui-
ally called “layer norm”).
Fig. 8.7 illustrates a transformer blo

--- Retrieved chunk 3 | score=0.7641 ---
e internal layers of a transformer.
26 CHAPTER 8 • T RANSFORMERS
8.10 Summary
This chapter has introduced the transformer and its components for the language
modeling task introduced in the previous chapter. Here’s a summary of the main
points that we covered:
• Transformers are non-recurrent networks based on multi-head attention, a
kind of self-attention. A multi-head attention computation takes an input
vector xi and maps it to an output ai by adding in vectors from prior tokens,
weighted by

In [51]:
from dotenv import load_dotenv
import os

load_dotenv()

groq_api_key = os.getenv("GROQ_API_KEY")


# load_dotenv(dotenv_path=Path.cwd() / ".env")

# groq_api_key = os.getenv("GROQ_API_KEY")
# if not groq_api_key:
#     raise ValueError("Please set GROQ_API_KEY in your .env file or environment.")

client = Groq(api_key=groq_api_key)
print("Groq client ready.")

Groq client ready.

answer generation function

In [52]:
def answer_question_naive(query, vector_db, top_k=3, model_name="llama-3.1-8b-instant"):
    retrieved = retrieve(query, vector_db, top_k=top_k)
    context = "\n\n".join([chunk for chunk, _ in retrieved])

    prompt = f"""
You are a helpful assistant answering questions strictly based on the provided context.

Context:
{context}

Question:
{query}

Instructions:
- Answer using only the provided context.
- If the answer is not in the context, say: "The answer is not found in the provided context."
- Keep the answer concise, around 1-3 sentences.
"""

    response = client.chat.completions.create(
        model=model_name,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    
    answer = response.choices[0].message.content.strip()
    return answer, retrieved

manual test of full naive RAG

In [53]:
question = "What is self-attention in a transformer?"
answer, retrieved = answer_question_naive(question, VECTOR_DB, top_k=3)

print("Question:", question)
print("\nAnswer:\n", answer)
print("\nRetrieved source chunks:\n")

for i, (chunk, score) in enumerate(retrieved, 1):
    print(f"--- Chunk {i} | score={score:.4f} ---")
    print(chunk[:1000])
    print()

Question: What is self-attention in a transformer?

Answer:
 Self-attention in a transformer can be thought of as a way to build contextual representations of a token's meaning by attending to and integrating information from surrounding tokens, helping the model learn how tokens relate to each other over large spans.

Retrieved source chunks:

--- Chunk 1 | score=0.8002 ---
ding and all the outputs from all
the previous layers and blocks.
The core intuition of the transformer, and the component that distinguishes it
from the feedforward layers we saw in Chapter 6, is this multi-head attention layer,
also called a self-attention layer. Attention can be thought of as a way to build
contextual representations of a token’s meaning by attending to and integrating
information from surrounding tokens, helping the model learn how tokens relate to
each other over large span

--- Chunk 2 | score=0.7966 ---
ther linear projection WO∈ RAdv×d to reshape it, resulting in the multi-head
attention vector ai with the correct output shape [1× d] at each input i.
8.2 Transformer Blocks
The self-attention calculation lies at the core of what’s called a transformer block,
which, in addition to the self-attention layer, includes three other kinds of layers: (1)
a feedforward layer, (2) residual connections, and (3) normalizing layers (colloqui-
ally called “layer norm”).
Fig. 8.7 illustrates a transformer blo

--- Chunk 3 | score=0.7641 ---
e internal layers of a transformer.
26 CHAPTER 8 • T RANSFORMERS
8.10 Summary
This chapter has introduced the transformer and its components for the language
modeling task introduced in the previous chapter. Here’s a summary of the main
points that we covered:
• Transformers are non-recurrent networks based on multi-head attention, a
kind of self-attention. A multi-head attention computation takes an input
vector xi and maps it to an output ai by adding in vectors from prior tokens,
weighted by

20 questions through naive RAG

In [ ]:
with open("answer/qa_pairs.json", "r", encoding="utf-8") as f:
    qa_pairs = json.load(f)

for item in tqdm(qa_pairs, desc="Running Naive RAG"):
    question = item["question"]
    answer, _ = answer_question_naive(question, VECTOR_DB, top_k=3)
    item["naive_rag_answer"] = answer

print("Naive RAG answers generated.")

Running Naive RAG: 100%|██████████| 20/20 [00:49<00:00,  2.45s/it]

Naive RAG answers generated.

In [55]:
with open("data/qa_pairs_with_naive_rag.json", "w", encoding="utf-8") as f:
    json.dump(qa_pairs, f, indent=2, ensure_ascii=False)

print("Saved Naive RAG results.")

Saved Naive RAG results.

Contextual Retrieval

contextual enrichment function

In [56]:
def enrich_chunk(chunk, document, title="Chapter 8: Transformers", model_name="llama-3.1-8b-instant"):
    prompt = f"""
Title: {title}

Document excerpt:
{document[:4000]}

Chunk:
{chunk}

Provide brief context in 1-2 sentences explaining what this chunk discusses in relation to the full document.
Format:
This chunk from {title} discusses ...
"""

    response = client.chat.completions.create(
        model=model_name,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    context = response.choices[0].message.content.strip()
    return f"{context}\n\n{chunk}"

build contextualized chunks

In [57]:
contextual_chunks = []

for chunk in tqdm(chunks, desc="Enriching chunks for Contextual Retrieval"):
    try:
        enriched_chunk = enrich_chunk(chunk, cleaned_text, title="Chapter 8: Transformers")
        contextual_chunks.append(enriched_chunk)
    except Exception as e:
        print("Error enriching chunk:", e)
        contextual_chunks.append(chunk)  # fallback to original chunk if error happens

    time.sleep(1)  # helps with Groq free-tier rate limits

print("Number of contextual chunks:", len(contextual_chunks))
print("\nSample contextual chunk:\n")
print(contextual_chunks[0][:1200])

Enriching chunks for Contextual Retrieval:   3%|▎         | 5/171 [01:30<1:05:11, 23.56s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499994, Requested 1024. Please try again in 2m55.9104s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   4%|▎         | 6/171 [01:31<43:48, 15.93s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499987, Requested 1024. Please try again in 2m54.7008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   4%|▍         | 7/171 [01:33<30:24, 11.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499981, Requested 1025. Please try again in 2m53.836799999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   5%|▍         | 8/171 [01:34<21:33,  7.94s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499974, Requested 1034. Please try again in 2m54.1824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   5%|▌         | 9/171 [01:35<15:39,  5.80s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499968, Requested 1042. Please try again in 2m54.528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   6%|▌         | 10/171 [01:36<11:40,  4.35s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499961, Requested 1023. Please try again in 2m50.0352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   6%|▋         | 11/171 [01:37<08:57,  3.36s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499955, Requested 1035. Please try again in 2m51.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   7%|▋         | 12/171 [01:38<07:05,  2.67s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499949, Requested 1082. Please try again in 2m58.1568s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   8%|▊         | 13/171 [01:39<05:47,  2.20s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499942, Requested 1031. Please try again in 2m48.1344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   8%|▊         | 14/171 [01:40<04:53,  1.87s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499936, Requested 1054. Please try again in 2m51.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   9%|▉         | 15/171 [01:41<04:17,  1.65s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499929, Requested 1040. Please try again in 2m47.4432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   9%|▉         | 16/171 [01:43<03:51,  1.49s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499923, Requested 1044. Please try again in 2m47.0976s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  10%|▉         | 17/171 [01:44<03:32,  1.38s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499916, Requested 1048. Please try again in 2m46.5792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  11%|█         | 18/171 [01:45<03:18,  1.30s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499910, Requested 1038. Please try again in 2m43.814399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  11%|█         | 19/171 [01:46<03:08,  1.24s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499903, Requested 1023. Please try again in 2m40.0128s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  12%|█▏        | 20/171 [01:47<03:02,  1.21s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499897, Requested 1054. Please try again in 2m44.3328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  12%|█▏        | 21/171 [01:48<02:56,  1.18s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499890, Requested 1031. Please try again in 2m39.1488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  13%|█▎        | 22/171 [01:49<02:52,  1.16s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499884, Requested 1046. Please try again in 2m40.704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  13%|█▎        | 23/171 [01:50<02:49,  1.14s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499877, Requested 1029. Please try again in 2m36.5568s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  14%|█▍        | 24/171 [01:52<02:52,  1.17s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499870, Requested 1031. Please try again in 2m35.6928s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  15%|█▍        | 25/171 [01:53<02:49,  1.16s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499864, Requested 1042. Please try again in 2m36.5568s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  15%|█▌        | 26/171 [01:54<02:46,  1.15s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499857, Requested 1054. Please try again in 2m37.4208s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  16%|█▌        | 27/171 [01:55<02:42,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499851, Requested 1049. Please try again in 2m35.519999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  16%|█▋        | 28/171 [01:56<02:40,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499845, Requested 1058. Please try again in 2m36.0384s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  17%|█▋        | 29/171 [01:57<02:38,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499838, Requested 1077. Please try again in 2m38.112s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  18%|█▊        | 30/171 [01:58<02:37,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499832, Requested 1045. Please try again in 2m31.545599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  18%|█▊        | 31/171 [01:59<02:36,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499825, Requested 1052. Please try again in 2m31.545599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  19%|█▊        | 32/171 [02:00<02:34,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499819, Requested 1026. Please try again in 2m26.016s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  19%|█▉        | 33/171 [02:02<02:33,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499812, Requested 1034. Please try again in 2m26.1888s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  20%|█▉        | 34/171 [02:03<02:32,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499806, Requested 1048. Please try again in 2m27.5712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  20%|██        | 35/171 [02:04<02:32,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499799, Requested 1046. Please try again in 2m26.016s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  21%|██        | 36/171 [02:05<02:30,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499793, Requested 1068. Please try again in 2m28.7808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  22%|██▏       | 37/171 [02:06<02:28,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499787, Requested 1084. Please try again in 2m30.5088s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  22%|██▏       | 38/171 [02:07<02:28,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499780, Requested 1136. Please try again in 2m38.2848s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  23%|██▎       | 39/171 [02:08<02:26,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499774, Requested 1090. Please try again in 2m29.2992s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  23%|██▎       | 40/171 [02:09<02:25,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499767, Requested 1057. Please try again in 2m22.3872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  24%|██▍       | 41/171 [02:10<02:23,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499761, Requested 1074. Please try again in 2m24.288s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  25%|██▍       | 42/171 [02:12<02:22,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499755, Requested 1020. Please try again in 2m13.919999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  25%|██▌       | 43/171 [02:13<02:21,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 1034. Please try again in 2m15.1296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  26%|██▌       | 44/171 [02:14<02:20,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 1110. Please try again in 2m27.2256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  26%|██▋       | 45/171 [02:15<02:20,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 1104. Please try again in 2m24.9792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  27%|██▋       | 46/171 [02:16<02:19,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 1051. Please try again in 2m14.783999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  27%|██▋       | 47/171 [02:17<02:18,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499722, Requested 1047. Please try again in 2m12.8832s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  28%|██▊       | 48/171 [02:18<02:16,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 1029. Please try again in 2m8.735999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  29%|██▊       | 49/171 [02:19<02:15,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 1023. Please try again in 2m6.4896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  29%|██▉       | 50/171 [02:21<02:15,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 1090. Please try again in 2m17.030399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  30%|██▉       | 51/171 [02:22<02:13,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499696, Requested 1083. Please try again in 2m14.6112s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  30%|███       | 52/171 [02:23<02:12,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499690, Requested 1067. Please try again in 2m10.809599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  31%|███       | 53/171 [02:24<02:10,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499684, Requested 1039. Please try again in 2m4.9344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  32%|███▏      | 54/171 [02:25<02:10,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499677, Requested 1040. Please try again in 2m3.8976s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  32%|███▏      | 55/171 [02:26<02:10,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499671, Requested 1059. Please try again in 2m6.143999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  33%|███▎      | 56/171 [02:27<02:08,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499664, Requested 1035. Please try again in 2m0.7872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  33%|███▎      | 57/171 [02:28<02:06,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499658, Requested 1039. Please try again in 2m0.4416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  34%|███▍      | 58/171 [02:29<02:05,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499651, Requested 1080. Please try again in 2m6.3168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  35%|███▍      | 59/171 [02:31<02:04,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499645, Requested 1075. Please try again in 2m4.416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  35%|███▌      | 60/171 [02:32<02:03,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499638, Requested 1106. Please try again in 2m8.5632s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  36%|███▌      | 61/171 [02:33<02:02,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499632, Requested 1030. Please try again in 1m54.3936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  36%|███▋      | 62/171 [02:34<02:00,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499625, Requested 1034. Please try again in 1m53.8752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  37%|███▋      | 63/171 [02:35<02:00,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499619, Requested 1044. Please try again in 1m54.566399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  37%|███▋      | 64/171 [02:36<01:59,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499613, Requested 1029. Please try again in 1m50.9376s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  38%|███▊      | 65/171 [02:37<01:58,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499606, Requested 1043. Please try again in 1m52.147199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  39%|███▊      | 66/171 [02:38<01:56,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499600, Requested 1033. Please try again in 1m49.3824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  39%|███▉      | 67/171 [02:39<01:55,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499593, Requested 1029. Please try again in 1m47.4816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  40%|███▉      | 68/171 [02:41<01:54,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499587, Requested 1045. Please try again in 1m49.2096s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  40%|████      | 69/171 [02:42<01:53,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499580, Requested 1062. Please try again in 1m50.9376s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  41%|████      | 70/171 [02:43<01:52,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499574, Requested 1134. Please try again in 2m2.3424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  42%|████▏     | 71/171 [02:44<01:51,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499567, Requested 1064. Please try again in 1m49.0368s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  42%|████▏     | 72/171 [02:45<01:50,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499561, Requested 1046. Please try again in 1m44.8896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  43%|████▎     | 73/171 [02:46<01:49,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499555, Requested 1065. Please try again in 1m47.136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  43%|████▎     | 74/171 [02:47<01:48,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499548, Requested 1165. Please try again in 2m3.2064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  44%|████▍     | 75/171 [02:48<01:46,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499542, Requested 1265. Please try again in 2m19.4496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  44%|████▍     | 76/171 [02:49<01:45,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499535, Requested 1109. Please try again in 1m51.2832s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  45%|████▌     | 77/171 [02:51<01:44,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499529, Requested 1043. Please try again in 1m38.8416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  46%|████▌     | 78/171 [02:52<01:43,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499522, Requested 1031. Please try again in 1m35.5584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  46%|████▌     | 79/171 [02:53<01:43,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499516, Requested 1076. Please try again in 1m42.297599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  47%|████▋     | 80/171 [02:54<01:41,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499509, Requested 1075. Please try again in 1m40.9152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  47%|████▋     | 81/171 [02:55<01:40,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499503, Requested 1083. Please try again in 1m41.2608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  48%|████▊     | 82/171 [02:56<01:39,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499497, Requested 1040. Please try again in 1m32.7936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  49%|████▊     | 83/171 [02:57<01:38,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499490, Requested 1088. Please try again in 1m39.8784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  49%|████▉     | 84/171 [02:58<01:36,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499484, Requested 1050. Please try again in 1m32.2752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  50%|████▉     | 85/171 [02:59<01:35,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499477, Requested 1037. Please try again in 1m28.8192s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  50%|█████     | 86/171 [03:01<01:34,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499471, Requested 1028. Please try again in 1m26.2272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  51%|█████     | 87/171 [03:02<01:33,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499464, Requested 1056. Please try again in 1m29.856s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  51%|█████▏    | 88/171 [03:03<01:31,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499458, Requested 1085. Please try again in 1m33.8304s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  52%|█████▏    | 89/171 [03:04<01:30,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499452, Requested 1109. Please try again in 1m36.9408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  53%|█████▎    | 90/171 [03:05<01:29,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499445, Requested 1130. Please try again in 1m39.36s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  53%|█████▎    | 91/171 [03:06<01:28,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499439, Requested 1019. Please try again in 1m19.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  54%|█████▍    | 92/171 [03:07<01:27,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499433, Requested 1026. Please try again in 1m19.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  54%|█████▍    | 93/171 [03:08<01:25,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499426, Requested 1061. Please try again in 1m24.1536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  55%|█████▍    | 94/171 [03:09<01:24,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499420, Requested 1036. Please try again in 1m18.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  56%|█████▌    | 95/171 [03:11<01:23,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499414, Requested 1019. Please try again in 1m14.8224s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  56%|█████▌    | 96/171 [03:12<01:22,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499407, Requested 1028. Please try again in 1m15.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  57%|█████▋    | 97/171 [03:13<01:21,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499401, Requested 1022. Please try again in 1m13.0944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  57%|█████▋    | 98/171 [03:14<01:20,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499393, Requested 1043. Please try again in 1m15.3408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  58%|█████▊    | 99/171 [03:15<01:23,  1.15s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499387, Requested 1041. Please try again in 1m13.9584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  58%|█████▊    | 100/171 [03:16<01:20,  1.14s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499381, Requested 1038. Please try again in 1m12.4032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  59%|█████▉    | 101/171 [03:17<01:19,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499374, Requested 1054. Please try again in 1m13.9584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  60%|█████▉    | 102/171 [03:18<01:17,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499368, Requested 1053. Please try again in 1m12.7488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  60%|██████    | 103/171 [03:20<01:16,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499361, Requested 1051. Please try again in 1m11.1936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  61%|██████    | 104/171 [03:21<01:15,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499355, Requested 1090. Please try again in 1m16.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  61%|██████▏   | 105/171 [03:22<01:13,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499348, Requested 1043. Please try again in 1m7.5648s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  62%|██████▏   | 106/171 [03:23<01:12,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499342, Requested 1046. Please try again in 1m7.0464s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  63%|██████▎   | 107/171 [03:24<01:11,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499335, Requested 1023. Please try again in 1m1.862399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  63%|██████▎   | 108/171 [03:25<01:10,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499329, Requested 1027. Please try again in 1m1.5168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  64%|██████▎   | 109/171 [03:26<01:09,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499322, Requested 1107. Please try again in 1m14.1312s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  64%|██████▍   | 110/171 [03:27<01:08,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499316, Requested 1054. Please try again in 1m3.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  65%|██████▌   | 112/171 [04:30<18:54, 19.23s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499994, Requested 1048. Please try again in 3m0.057599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  66%|██████▌   | 113/171 [04:31<13:19, 13.79s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499988, Requested 1042. Please try again in 2m57.984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  67%|██████▋   | 114/171 [04:32<09:29,  9.98s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499981, Requested 1032. Please try again in 2m55.0464s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  67%|██████▋   | 115/171 [04:33<06:49,  7.32s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499975, Requested 1049. Please try again in 2m56.947199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  68%|██████▊   | 116/171 [04:34<05:00,  5.46s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499969, Requested 1035. Please try again in 2m53.4912s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  68%|██████▊   | 117/171 [04:35<03:43,  4.15s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499962, Requested 1022. Please try again in 2m50.0352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  69%|██████▉   | 118/171 [04:37<02:51,  3.23s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499956, Requested 1052. Please try again in 2m54.1824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  70%|██████▉   | 119/171 [04:38<02:14,  2.59s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499950, Requested 1248. Please try again in 3m27.0144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  70%|███████   | 120/171 [04:39<01:49,  2.15s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499943, Requested 1262. Please try again in 3m28.224s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  71%|███████   | 121/171 [04:40<01:31,  1.83s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499937, Requested 1203. Please try again in 3m16.992s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  71%|███████▏  | 122/171 [04:41<01:19,  1.61s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499930, Requested 1059. Please try again in 2m50.8992s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  72%|███████▏  | 123/171 [04:42<01:10,  1.46s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499924, Requested 1039. Please try again in 2m46.4064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  73%|███████▎  | 124/171 [04:43<01:03,  1.35s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499918, Requested 1029. Please try again in 2m43.6416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  73%|███████▎  | 125/171 [04:44<00:58,  1.28s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499911, Requested 1076. Please try again in 2m50.5536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  74%|███████▎  | 126/171 [04:45<00:55,  1.22s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499905, Requested 1105. Please try again in 2m54.528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  74%|███████▍  | 127/171 [04:46<00:52,  1.19s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499899, Requested 1045. Please try again in 2m43.1232s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  75%|███████▍  | 128/171 [04:48<00:49,  1.16s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499892, Requested 1064. Please try again in 2m45.1968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  75%|███████▌  | 129/171 [04:49<00:48,  1.14s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499886, Requested 1045. Please try again in 2m40.8768s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  76%|███████▌  | 130/171 [04:50<00:46,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499879, Requested 1074. Please try again in 2m44.678399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  77%|███████▋  | 131/171 [04:51<00:44,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499873, Requested 1145. Please try again in 2m55.9104s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  77%|███████▋  | 132/171 [04:52<00:43,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499867, Requested 1038. Please try again in 2m36.384s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  78%|███████▊  | 133/171 [04:53<00:42,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499860, Requested 1048. Please try again in 2m36.9024s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  78%|███████▊  | 134/171 [04:54<00:40,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499854, Requested 1040. Please try again in 2m34.4832s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  79%|███████▉  | 135/171 [04:55<00:39,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499848, Requested 1057. Please try again in 2m36.384s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  80%|███████▉  | 136/171 [04:56<00:38,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499841, Requested 1055. Please try again in 2m34.8288s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  80%|████████  | 137/171 [04:57<00:37,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499835, Requested 1074. Please try again in 2m37.0752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  81%|████████  | 138/171 [04:59<00:36,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499829, Requested 1055. Please try again in 2m32.7552s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  81%|████████▏ | 139/171 [05:00<00:35,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499822, Requested 1031. Please try again in 2m27.3984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  82%|████████▏ | 140/171 [05:01<00:34,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499816, Requested 1027. Please try again in 2m25.6704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  82%|████████▏ | 141/171 [05:02<00:33,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499809, Requested 1035. Please try again in 2m25.8432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  83%|████████▎ | 142/171 [05:03<00:31,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499803, Requested 1049. Please try again in 2m27.2256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  84%|████████▎ | 143/171 [05:04<00:30,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499797, Requested 1040. Please try again in 2m24.6336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  84%|████████▍ | 144/171 [05:05<00:29,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499790, Requested 1050. Please try again in 2m25.152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  85%|████████▍ | 145/171 [05:06<00:28,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499784, Requested 1043. Please try again in 2m22.9056s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  85%|████████▌ | 146/171 [05:07<00:27,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499777, Requested 1073. Please try again in 2m26.88s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  86%|████████▌ | 147/171 [05:09<00:26,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499771, Requested 1065. Please try again in 2m24.4608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  87%|████████▋ | 148/171 [05:10<00:25,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499765, Requested 1050. Please try again in 2m20.832s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  87%|████████▋ | 149/171 [05:11<00:24,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499758, Requested 1054. Please try again in 2m20.3136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  88%|████████▊ | 150/171 [05:12<00:23,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499752, Requested 1055. Please try again in 2m19.4496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  88%|████████▊ | 151/171 [05:13<00:22,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 1080. Please try again in 2m22.7328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  89%|████████▉ | 152/171 [05:14<00:20,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 1057. Please try again in 2m17.5488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  89%|████████▉ | 153/171 [05:15<00:19,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 1049. Please try again in 2m15.1296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  90%|█████████ | 154/171 [05:16<00:18,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499726, Requested 1042. Please try again in 2m12.7104s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  91%|█████████ | 155/171 [05:17<00:17,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499720, Requested 1043. Please try again in 2m11.846399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  91%|█████████ | 156/171 [05:18<00:16,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 1044. Please try again in 2m10.9824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  92%|█████████▏| 157/171 [05:20<00:15,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 1030. Please try again in 2m7.3536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  92%|█████████▏| 158/171 [05:21<00:14,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 1031. Please try again in 2m6.4896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  93%|█████████▎| 159/171 [05:22<00:13,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499695, Requested 1022. Please try again in 2m3.8976s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  94%|█████████▎| 160/171 [05:23<00:12,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499688, Requested 1025. Please try again in 2m3.2064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  94%|█████████▍| 161/171 [05:24<00:11,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499682, Requested 1034. Please try again in 2m3.724799999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  95%|█████████▍| 162/171 [05:25<00:09,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499675, Requested 1042. Please try again in 2m3.8976s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  95%|█████████▌| 163/171 [05:26<00:08,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499669, Requested 1037. Please try again in 2m1.9968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  96%|█████████▌| 164/171 [05:27<00:07,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499663, Requested 1103. Please try again in 2m12.3648s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  96%|█████████▋| 165/171 [05:28<00:06,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499656, Requested 1128. Please try again in 2m15.4752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  97%|█████████▋| 166/171 [05:29<00:05,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499650, Requested 1113. Please try again in 2m11.846399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  98%|█████████▊| 167/171 [05:31<00:04,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499644, Requested 1098. Please try again in 2m8.2176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  98%|█████████▊| 168/171 [05:32<00:03,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499637, Requested 1089. Please try again in 2m5.4528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  99%|█████████▉| 169/171 [05:33<00:02,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499631, Requested 1098. Please try again in 2m5.9712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  99%|█████████▉| 170/171 [05:34<00:01,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499625, Requested 1033. Please try again in 1m53.7024s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval: 100%|██████████| 171/171 [05:35<00:00,  1.96s/it]

Number of contextual chunks: 171

Sample contextual chunk:

This chunk from Chapter 8: Transformers discusses the introduction of the transformer architecture, a standard architecture for building large language models, and its impact on the field of speech and language processing.

Speech and Language Processing. Daniel Jurafsky & James H. Martin. Copyright © 2026. All
rights reserved. Draft of January 6, 2026.
CHAPTER
8
Transformers
“The true art of memory is the art of attention ”
Samuel Johnson, Idler #74, September 1759
In this chapter we introduce thetransformer, the standard architecture for build-
ing large language models. As we discussed in the prior chapter, transformer-based
large language models have completely changed the ﬁeld of speech and language
processing

build contextual vector database

In [58]:
contextual_chunks = []

for chunk in tqdm(chunks, desc="Enriching chunks for Contextual Retrieval"):
    try:
        enriched_chunk = enrich_chunk(chunk, cleaned_text, title="Chapter 8: Transformers")
        contextual_chunks.append(enriched_chunk)
    except Exception as e:
        print("Error enriching chunk:", e)
        contextual_chunks.append(chunk)  # fallback to original chunk if error happens

    time.sleep(1)  # helps with Groq free-tier rate limits

print("Number of contextual chunks:", len(contextual_chunks))
print("\nSample contextual chunk:\n")
print(contextual_chunks[0][:1200])

Enriching chunks for Contextual Retrieval:   0%|          | 0/171 [00:00<?, ?it/s]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499618, Requested 1039. Please try again in 1m53.5296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   1%|          | 1/171 [00:01<03:06,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499612, Requested 1034. Please try again in 1m51.6288s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   1%|          | 2/171 [00:02<03:10,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499605, Requested 1038. Please try again in 1m51.1104s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   2%|▏         | 3/171 [00:03<03:06,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499599, Requested 1028. Please try again in 1m48.345599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   2%|▏         | 4/171 [00:04<03:04,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499592, Requested 1032. Please try again in 1m47.8272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   3%|▎         | 5/171 [00:05<03:03,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499586, Requested 1024. Please try again in 1m45.408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   4%|▎         | 6/171 [00:06<03:01,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499580, Requested 1024. Please try again in 1m44.3712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   4%|▍         | 7/171 [00:07<03:00,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499573, Requested 1025. Please try again in 1m43.3344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   5%|▍         | 8/171 [00:08<02:59,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499567, Requested 1034. Please try again in 1m43.8528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   5%|▌         | 9/171 [00:09<02:57,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499561, Requested 1042. Please try again in 1m44.1984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   6%|▌         | 10/171 [00:11<02:57,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499554, Requested 1023. Please try again in 1m39.7056s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   6%|▋         | 11/171 [00:12<02:55,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499548, Requested 1035. Please try again in 1m40.742399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   7%|▋         | 12/171 [00:13<02:54,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499542, Requested 1082. Please try again in 1m47.8272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   8%|▊         | 13/171 [00:14<02:53,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499535, Requested 1031. Please try again in 1m37.8048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   8%|▊         | 14/171 [00:15<02:52,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499529, Requested 1054. Please try again in 1m40.742399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   9%|▉         | 15/171 [00:16<02:52,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499522, Requested 1040. Please try again in 1m37.1136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:   9%|▉         | 16/171 [00:17<02:51,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499516, Requested 1044. Please try again in 1m36.767999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  10%|▉         | 17/171 [00:18<02:49,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499510, Requested 1048. Please try again in 1m36.4224s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  11%|█         | 18/171 [00:19<02:48,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499503, Requested 1038. Please try again in 1m33.4848s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  11%|█         | 19/171 [00:20<02:47,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499497, Requested 1023. Please try again in 1m29.856s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  12%|█▏        | 20/171 [00:22<02:45,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499491, Requested 1054. Please try again in 1m34.176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  12%|█▏        | 21/171 [00:23<02:44,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499484, Requested 1031. Please try again in 1m28.992s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  13%|█▎        | 22/171 [00:24<02:43,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499478, Requested 1046. Please try again in 1m30.5472s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  13%|█▎        | 23/171 [00:25<02:42,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499472, Requested 1029. Please try again in 1m26.5728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  14%|█▍        | 24/171 [00:26<02:41,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499465, Requested 1031. Please try again in 1m25.7088s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  15%|█▍        | 25/171 [00:27<02:40,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499459, Requested 1042. Please try again in 1m26.5728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  15%|█▌        | 26/171 [00:28<02:39,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499452, Requested 1054. Please try again in 1m27.4368s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  16%|█▌        | 27/171 [00:29<02:41,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499445, Requested 1049. Please try again in 1m25.363199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  16%|█▋        | 28/171 [00:30<02:41,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499439, Requested 1058. Please try again in 1m25.8816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  17%|█▋        | 29/171 [00:32<02:39,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499433, Requested 1077. Please try again in 1m28.128s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  18%|█▊        | 30/171 [00:33<02:37,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499426, Requested 1045. Please try again in 1m21.3888s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  18%|█▊        | 31/171 [00:34<02:35,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499420, Requested 1052. Please try again in 1m21.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  19%|█▊        | 32/171 [00:35<02:33,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499414, Requested 1026. Please try again in 1m16.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  19%|█▉        | 33/171 [00:36<02:32,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499407, Requested 1034. Please try again in 1m16.204799999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  20%|█▉        | 34/171 [00:37<02:31,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499401, Requested 1048. Please try again in 1m17.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  20%|██        | 35/171 [00:38<02:29,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499394, Requested 1046. Please try again in 1m16.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  21%|██        | 36/171 [00:39<02:29,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499388, Requested 1068. Please try again in 1m18.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  22%|██▏       | 37/171 [00:40<02:28,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499382, Requested 1084. Please try again in 1m20.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  22%|██▏       | 38/171 [00:41<02:26,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499375, Requested 1136. Please try again in 1m28.3008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  23%|██▎       | 39/171 [00:43<02:25,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499369, Requested 1090. Please try again in 1m19.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  23%|██▎       | 40/171 [00:44<02:24,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499362, Requested 1057. Please try again in 1m12.4032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  24%|██▍       | 41/171 [00:45<02:23,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499356, Requested 1074. Please try again in 1m14.304s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  25%|██▍       | 42/171 [00:46<02:22,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499350, Requested 1020. Please try again in 1m3.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  25%|██▌       | 43/171 [00:47<02:20,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499343, Requested 1034. Please try again in 1m5.1456s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  26%|██▌       | 44/171 [00:48<02:19,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499337, Requested 1110. Please try again in 1m17.2416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  26%|██▋       | 45/171 [00:49<02:18,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499331, Requested 1104. Please try again in 1m15.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  27%|██▋       | 46/171 [00:50<02:17,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499324, Requested 1051. Please try again in 1m4.8s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  27%|██▋       | 47/171 [00:51<02:16,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499318, Requested 1047. Please try again in 1m3.071999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  29%|██▊       | 49/171 [01:53<38:27, 18.92s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499994, Requested 1023. Please try again in 2m55.7376s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  29%|██▉       | 50/171 [01:54<27:22, 13.57s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499988, Requested 1090. Please try again in 3m6.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  30%|██▉       | 51/171 [01:55<19:39,  9.83s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499981, Requested 1083. Please try again in 3m3.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  30%|███       | 52/171 [01:56<14:17,  7.21s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499975, Requested 1067. Please try again in 3m0.057599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  31%|███       | 53/171 [01:57<10:34,  5.38s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499969, Requested 1039. Please try again in 2m54.1824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  32%|███▏      | 54/171 [01:58<07:58,  4.09s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499955, Requested 1040. Please try again in 2m51.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  32%|███▏      | 55/171 [02:01<06:55,  3.58s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499946, Requested 1059. Please try again in 2m53.664s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  33%|███▎      | 56/171 [02:02<05:38,  2.95s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499940, Requested 1035. Please try again in 2m48.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  33%|███▎      | 57/171 [02:03<04:32,  2.39s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499934, Requested 1039. Please try again in 2m48.1344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  34%|███▍      | 58/171 [02:04<03:46,  2.00s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499927, Requested 1080. Please try again in 2m54.0096s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  35%|███▍      | 59/171 [02:06<03:13,  1.73s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499921, Requested 1075. Please try again in 2m52.108799999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  35%|███▌      | 60/171 [02:07<02:50,  1.54s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499915, Requested 1106. Please try again in 2m56.4288s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  36%|███▌      | 61/171 [02:08<02:34,  1.41s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499908, Requested 1030. Please try again in 2m42.0864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  36%|███▋      | 62/171 [02:09<02:23,  1.31s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499902, Requested 1034. Please try again in 2m41.7408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  37%|███▋      | 63/171 [02:10<02:14,  1.25s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499896, Requested 1044. Please try again in 2m42.432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  37%|███▋      | 64/171 [02:11<02:08,  1.20s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499889, Requested 1029. Please try again in 2m38.6304s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  38%|███▊      | 65/171 [02:12<02:04,  1.17s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499883, Requested 1043. Please try again in 2m40.0128s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  39%|███▊      | 66/171 [02:13<02:00,  1.15s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499877, Requested 1033. Please try again in 2m37.248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  39%|███▉      | 67/171 [02:14<01:57,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499870, Requested 1029. Please try again in 2m35.3472s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  40%|███▉      | 68/171 [02:15<01:55,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499864, Requested 1045. Please try again in 2m37.0752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  40%|████      | 69/171 [02:17<01:53,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499857, Requested 1062. Please try again in 2m38.8032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  41%|████      | 70/171 [02:18<01:53,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499851, Requested 1134. Please try again in 2m50.208s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  42%|████▏     | 71/171 [02:19<01:51,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499844, Requested 1064. Please try again in 2m36.9024s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  42%|████▏     | 72/171 [02:20<01:54,  1.16s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499837, Requested 1046. Please try again in 2m32.5824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  43%|████▎     | 73/171 [02:21<01:51,  1.14s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499831, Requested 1065. Please try again in 2m34.8288s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  43%|████▎     | 74/171 [02:22<01:49,  1.13s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499825, Requested 1165. Please try again in 2m51.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  44%|████▍     | 75/171 [02:23<01:47,  1.12s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499818, Requested 1265. Please try again in 3m7.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  44%|████▍     | 76/171 [02:24<01:45,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499812, Requested 1109. Please try again in 2m39.1488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  45%|████▌     | 77/171 [02:26<01:44,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499806, Requested 1043. Please try again in 2m26.7072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  46%|████▌     | 78/171 [02:27<01:42,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499799, Requested 1031. Please try again in 2m23.424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  46%|████▌     | 79/171 [02:28<01:42,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499793, Requested 1076. Please try again in 2m30.1632s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  47%|████▋     | 80/171 [02:29<01:40,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499786, Requested 1075. Please try again in 2m28.7808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  47%|████▋     | 81/171 [02:30<01:39,  1.11s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499780, Requested 1083. Please try again in 2m29.1264s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  48%|████▊     | 82/171 [02:31<01:38,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499774, Requested 1040. Please try again in 2m20.6592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  49%|████▊     | 83/171 [02:32<01:37,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499767, Requested 1088. Please try again in 2m27.744s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  49%|████▉     | 84/171 [02:33<01:35,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499761, Requested 1050. Please try again in 2m20.140799999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  50%|████▉     | 85/171 [02:34<01:34,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499755, Requested 1037. Please try again in 2m16.857599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  50%|█████     | 86/171 [02:35<01:33,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 1028. Please try again in 2m14.0928s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  51%|█████     | 87/171 [02:37<01:32,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 1056. Please try again in 2m17.8944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  51%|█████▏    | 88/171 [02:38<01:31,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 1085. Please try again in 2m21.696s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  52%|█████▏    | 89/171 [02:39<01:30,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 1109. Please try again in 2m24.8064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  53%|█████▎    | 90/171 [02:40<01:28,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 1130. Please try again in 2m27.3984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  53%|█████▎    | 91/171 [02:41<01:27,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 1019. Please try again in 2m7.008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  54%|█████▍    | 92/171 [02:42<01:26,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 1026. Please try again in 2m7.1808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  54%|█████▍    | 93/171 [02:43<01:25,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 1061. Please try again in 2m12.191999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  55%|█████▍    | 94/171 [02:44<01:24,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499697, Requested 1036. Please try again in 2m6.6624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  56%|█████▌    | 95/171 [02:45<01:23,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499691, Requested 1019. Please try again in 2m2.688s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  56%|█████▌    | 96/171 [02:46<01:22,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499685, Requested 1028. Please try again in 2m3.2064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  57%|█████▋    | 97/171 [02:48<01:21,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499678, Requested 1022. Please try again in 2m0.96s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  57%|█████▋    | 98/171 [02:49<01:20,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499672, Requested 1043. Please try again in 2m3.552s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  58%|█████▊    | 99/171 [02:50<01:19,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499666, Requested 1041. Please try again in 2m2.169599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  58%|█████▊    | 100/171 [02:51<01:18,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499659, Requested 1038. Please try again in 2m0.4416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  59%|█████▉    | 101/171 [02:52<01:16,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499653, Requested 1054. Please try again in 2m2.169599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  60%|█████▉    | 102/171 [02:53<01:15,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499647, Requested 1053. Please try again in 2m0.96s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  60%|██████    | 103/171 [02:54<01:14,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499640, Requested 1051. Please try again in 1m59.4048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  61%|██████    | 104/171 [02:55<01:13,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499634, Requested 1090. Please try again in 2m5.1072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  61%|██████▏   | 105/171 [02:56<01:12,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499627, Requested 1043. Please try again in 1m55.776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  62%|██████▏   | 106/171 [02:57<01:11,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499621, Requested 1046. Please try again in 1m55.2576s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  63%|██████▎   | 107/171 [02:59<01:10,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499615, Requested 1023. Please try again in 1m50.2464s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  63%|██████▎   | 108/171 [03:00<01:09,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499608, Requested 1027. Please try again in 1m49.728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  64%|██████▎   | 109/171 [03:01<01:07,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499602, Requested 1107. Please try again in 2m2.5152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  64%|██████▍   | 110/171 [03:02<01:06,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499596, Requested 1054. Please try again in 1m52.32s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  65%|██████▍   | 111/171 [03:03<01:05,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499589, Requested 1035. Please try again in 1m47.8272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  65%|██████▌   | 112/171 [03:04<01:04,  1.09s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499583, Requested 1048. Please try again in 1m49.0368s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  66%|██████▌   | 113/171 [03:05<01:03,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499577, Requested 1042. Please try again in 1m46.9632s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  67%|██████▋   | 114/171 [03:06<01:02,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499570, Requested 1032. Please try again in 1m44.0256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  67%|██████▋   | 115/171 [03:07<01:01,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499564, Requested 1049. Please try again in 1m45.9264s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  68%|██████▊   | 116/171 [03:08<01:00,  1.09s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499558, Requested 1035. Please try again in 1m42.4704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  68%|██████▊   | 117/171 [03:09<00:59,  1.10s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499551, Requested 1022. Please try again in 1m39.0144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  69%|██████▉   | 118/171 [03:11<00:57,  1.09s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499545, Requested 1052. Please try again in 1m43.1616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  70%|██████▉   | 119/171 [03:12<00:56,  1.09s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499539, Requested 1248. Please try again in 2m15.9936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  70%|███████   | 120/171 [03:13<00:55,  1.09s/it]

Error enriching chunk: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499532, Requested 1262. Please try again in 2m17.2032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Enriching chunks for Contextual Retrieval:  70%|███████   | 120/171 [03:14<01:22,  1.62s/it]

KeyboardInterrupt:

In [ ]:
VECTOR_DB_CONTEXTUAL = []

for chunk in tqdm(contextual_chunks, desc="Embedding contextual chunks"):
    emb = get_embedding(chunk)
    VECTOR_DB_CONTEXTUAL.append((chunk, emb))

print("Contextual Vector DB size:", len(VECTOR_DB_CONTEXTUAL))
print("Embedding dimension:", VECTOR_DB_CONTEXTUAL[0][1].shape)

Embedding contextual chunks: 100%|██████████| 171/171 [00:11<00:00, 14.98it/s]

Contextual Vector DB size: 171
Embedding dimension: (384,)

retrieval test for contextual DB

In [ ]:
test_question = "What is self-attention in a transformer?"
retrieved_contextual = retrieve(test_question, VECTOR_DB_CONTEXTUAL, top_k=3)

print("Question:", test_question)
print()

for i, (chunk, score) in enumerate(retrieved_contextual, 1):
    print(f"--- Contextual chunk {i} | score={score:.4f} ---")
    print(chunk[:1200])
    print()

Question: What is self-attention in a transformer?

--- Contextual chunk 1 | score=0.8002 ---
ding and all the outputs from all
the previous layers and blocks.
The core intuition of the transformer, and the component that distinguishes it
from the feedforward layers we saw in Chapter 6, is this multi-head attention layer,
also called a self-attention layer. Attention can be thought of as a way to build
contextual representations of a token’s meaning by attending to and integrating
information from surrounding tokens, helping the model learn how tokens relate to
each other over large span

--- Contextual chunk 2 | score=0.7966 ---
ther linear projection WO∈ RAdv×d to reshape it, resulting in the multi-head
attention vector ai with the correct output shape [1× d] at each input i.
8.2 Transformer Blocks
The self-attention calculation lies at the core of what’s called a transformer block,
which, in addition to the self-attention layer, includes three other kinds of layers: (1)
a feedforward layer, (2) residual connections, and (3) normalizing layers (colloqui-
ally called “layer norm”).
Fig. 8.7 illustrates a transformer blo

--- Contextual chunk 3 | score=0.7641 ---
e internal layers of a transformer.
26 CHAPTER 8 • T RANSFORMERS
8.10 Summary
This chapter has introduced the transformer and its components for the language
modeling task introduced in the previous chapter. Here’s a summary of the main
points that we covered:
• Transformers are non-recurrent networks based on multi-head attention, a
kind of self-attention. A multi-head attention computation takes an input
vector xi and maps it to an output ai by adding in vectors from prior tokens,
weighted by

answer function for contextual retrieval

In [ ]:
def answer_question_contextual(query, vector_db, top_k=3, model_name="llama-3.1-8b-instant"):
    retrieved = retrieve(query, vector_db, top_k=top_k)
    context = "\n\n".join([chunk for chunk, _ in retrieved])

    prompt = f"""
You are a helpful assistant answering questions strictly based on the provided context.

Context:
{context}

Question:
{query}

Instructions:
- Answer using only the provided context.
- If the answer is not found in the context, say: "The answer is not found in the provided context."
- Keep the answer concise, around 1-3 sentences.
"""

    response = client.chat.completions.create(
        model=model_name,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    answer = response.choices[0].message.content.strip()
    return answer, retrieved

test one contextual answer

In [ ]:
test_question = "What is self-attention in a transformer?"
test_answer_contextual, test_retrieved_contextual = answer_question_contextual(
    test_question, VECTOR_DB_CONTEXTUAL, top_k=3
)

print("Question:", test_question)
print("\nContextual Retrieval Answer:\n")
print(test_answer_contextual)

print("\nRetrieved contextual chunks:\n")
for i, (chunk, score) in enumerate(test_retrieved_contextual, 1):
    print(f"--- Chunk {i} | score={score:.4f} ---")
    print(chunk[:1200])
    print()

Question: What is self-attention in a transformer?

Contextual Retrieval Answer:

Self-attention in a transformer is a way to build contextual representations of a token's meaning by attending to and integrating information from surrounding tokens, helping the model learn how tokens relate to each other over large spans. It is a multi-head attention computation that takes an input vector and maps it to an output by adding in vectors from prior tokens, weighted by their relevance.

Retrieved contextual chunks:

--- Chunk 1 | score=0.8002 ---
ding and all the outputs from all
the previous layers and blocks.
The core intuition of the transformer, and the component that distinguishes it
from the feedforward layers we saw in Chapter 6, is this multi-head attention layer,
also called a self-attention layer. Attention can be thought of as a way to build
contextual representations of a token’s meaning by attending to and integrating
information from surrounding tokens, helping the model learn how tokens relate to
each other over large span

--- Chunk 2 | score=0.7966 ---
ther linear projection WO∈ RAdv×d to reshape it, resulting in the multi-head
attention vector ai with the correct output shape [1× d] at each input i.
8.2 Transformer Blocks
The self-attention calculation lies at the core of what’s called a transformer block,
which, in addition to the self-attention layer, includes three other kinds of layers: (1)
a feedforward layer, (2) residual connections, and (3) normalizing layers (colloqui-
ally called “layer norm”).
Fig. 8.7 illustrates a transformer blo

--- Chunk 3 | score=0.7641 ---
e internal layers of a transformer.
26 CHAPTER 8 • T RANSFORMERS
8.10 Summary
This chapter has introduced the transformer and its components for the language
modeling task introduced in the previous chapter. Here’s a summary of the main
points that we covered:
• Transformers are non-recurrent networks based on multi-head attention, a
kind of self-attention. A multi-head attention computation takes an input
vector xi and maps it to an output ai by adding in vectors from prior tokens,
weighted by

run contextual retrieval for all 20 questions

In [ ]:
for item in tqdm(qa_pairs, desc="Running Contextual Retrieval"):
    question = item["question"]

    try:
        answer, retrieved = answer_question_contextual(question, VECTOR_DB_CONTEXTUAL, top_k=3)
        item["contextual_retrieval_answer"] = answer
        item["contextual_retrieval_sources"] = [chunk for chunk, _ in retrieved]
    except Exception as e:
        item["contextual_retrieval_answer"] = f"ERROR: {str(e)}"
        item["contextual_retrieval_sources"] = []

    time.sleep(1)  # helps with rate limits

print("Finished generating Contextual Retrieval answers.")

Running Contextual Retrieval: 100%|██████████| 20/20 [02:12<00:00,  6.61s/it]

Finished generating Contextual Retrieval answers.

In [ ]:
with open("answer/qa_pairs_with_both_methods.json", "w", encoding="utf-8") as f:
    json.dump(qa_pairs, f, indent=2, ensure_ascii=False)

print("Saved results with Naive RAG and Contextual Retrieval.")

Saved results with Naive RAG and Contextual Retrieval.

quick comparison check

In [ ]:
print("nee")

nee

In [ ]:
for i in range(3):
    print(f"Q{i+1}: {qa_pairs[i]['question']}")
    print("Ground truth:", qa_pairs[i]["ground_truth_answer"])
    print("Naive RAG:", qa_pairs[i]["naive_rag_answer"])
    print("Contextual Retrieval:", qa_pairs[i]["contextual_retrieval_answer"])
    print("-" * 100)

Q1: What is the primary purpose of the self-attention mechanism in a transformer?
Ground truth: Self-attention allows a model to build contextual representations of a token by integrating information from other tokens in the sequence.
Naive RAG: The primary purpose of the self-attention mechanism in a transformer is to build contextual representations of a token's meaning by attending to and integrating information from surrounding tokens, helping the model learn how tokens relate to each other over large spans.
Contextual Retrieval: The primary purpose of the self-attention mechanism in a transformer is to build contextual representations of a token's meaning by attending to and integrating information from surrounding tokens, helping the model learn how tokens relate to each other over large spans.
----------------------------------------------------------------------------------------------------
Q2: In the attention mechanism, what roles do the query, key, and value vectors play?
Ground truth: The query represents the current token being compared, the key represents tokens used for similarity comparison, and the value contains the information that is weighted and combined in the output.
Naive RAG: The query, key, and value vectors play the following roles in the attention mechanism:

The query vector is used to match keys representing content in an associative memory.
The key vector represents content in an associative memory.
The value vector is used to compute the weighted sum that is our a3.
Contextual Retrieval: ERROR: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499994, Requested 548. Please try again in 1m33.657599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
----------------------------------------------------------------------------------------------------
Q3: Why is a scaling factor used in the dot product of query and key vectors?
Ground truth: The dot product is scaled by the square root of the key dimension to prevent large values that could cause unstable gradients during training.
Naive RAG: Exponentiating large values can lead to numerical issues and loss of gradients during training. To avoid this, the dot product is scaled by a factor related to the size of the embeddings, specifically by dividing by the square root of the dimensionality of the query and key vectors (dk).
Contextual Retrieval: ERROR: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01km59edw5eaksgmrc9f2xwfrp` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499987, Requested 499. Please try again in 1m23.9808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
----------------------------------------------------------------------------------------------------

In [ ]:
from rouge_score import rouge_scorer

with open("data/qa_pairs_with_both_methods.json", "r", encoding="utf-8") as f:
    qa_pairs = json.load(f)

print("Loaded QA pairs:", len(qa_pairs))
print(qa_pairs[0].keys())

Loaded QA pairs: 20
dict_keys(['question', 'ground_truth_answer', 'naive_rag_answer', 'contextual_retrieval_answer', 'contextual_retrieval_sources'])

In [ ]:
scorer = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)

In [ ]:
results = []

for item in qa_pairs:
    question = item["question"]
    ground_truth = item["ground_truth_answer"]
    naive_answer = item["naive_rag_answer"]
    contextual_answer = item["contextual_retrieval_answer"]

    naive_scores = scorer.score(ground_truth, naive_answer)
    contextual_scores = scorer.score(ground_truth, contextual_answer)

    results.append({
        "question": question,
        "ground_truth_answer": ground_truth,
        "naive_rag_answer": naive_answer,
        "contextual_retrieval_answer": contextual_answer,

        "naive_rouge1": naive_scores["rouge1"].fmeasure,
        "naive_rouge2": naive_scores["rouge2"].fmeasure,
        "naive_rougeL": naive_scores["rougeL"].fmeasure,

        "contextual_rouge1": contextual_scores["rouge1"].fmeasure,
        "contextual_rouge2": contextual_scores["rouge2"].fmeasure,
        "contextual_rougeL": contextual_scores["rougeL"].fmeasure,
    })

print("Computed ROUGE for all questions.")

Computed ROUGE for all questions.

In [ ]:
df_results = pd.DataFrame(results)
df_results.head()

,question,ground_truth_answer,naive_rag_answer,contextual_retrieval_answer,naive_rouge1,naive_rouge2,naive_rougeL,contextual_rouge1,contextual_rouge2,contextual_rougeL
0,What is the primary purpose of the self-attent...,Self-attention allows a model to build context...,The primary purpose of the self-attention mech...,The primary purpose of the self-attention mech...,0.593750,0.290323,0.500000,0.593750,0.290323,0.500000
1,"In the attention mechanism, what roles do the ...",The query represents the current token being c...,"The query, key, and value vectors play the fol...",ERROR: Error code: 429 - {'error': {'message':...,0.419753,0.151899,0.271605,0.108696,0.000000,0.065217
2,Why is a scaling factor used in the dot produc...,The dot product is scaled by the square root o...,Exponentiating large values can lead to numeri...,ERROR: Error code: 429 - {'error': {'message':...,0.493151,0.366197,0.328767,0.023256,0.000000,0.023256
3,Why do transformers use multi-head attention i...,Multi-head attention allows the model to atten...,Transformers use multi-head attention instead ...,ERROR: Error code: 429 - {'error': {'message':...,0.472222,0.142857,0.250000,0.120482,0.000000,0.072289
4,What components are included in a standard tra...,A transformer block includes a multi-head self...,A standard transformer block consists of a res...,ERROR: Error code: 429 - {'error': {'message':...,0.447761,0.215385,0.388060,0.000000,0.000000,0.000000

In [ ]:
df_results = pd.DataFrame(results)
df_results.head()

,question,ground_truth_answer,naive_rag_answer,contextual_retrieval_answer,naive_rouge1,naive_rouge2,naive_rougeL,contextual_rouge1,contextual_rouge2,contextual_rougeL
0,What is the primary purpose of the self-attent...,Self-attention allows a model to build context...,The primary purpose of the self-attention mech...,The primary purpose of the self-attention mech...,0.593750,0.290323,0.500000,0.593750,0.290323,0.500000
1,"In the attention mechanism, what roles do the ...",The query represents the current token being c...,"The query, key, and value vectors play the fol...",ERROR: Error code: 429 - {'error': {'message':...,0.419753,0.151899,0.271605,0.108696,0.000000,0.065217
2,Why is a scaling factor used in the dot produc...,The dot product is scaled by the square root o...,Exponentiating large values can lead to numeri...,ERROR: Error code: 429 - {'error': {'message':...,0.493151,0.366197,0.328767,0.023256,0.000000,0.023256
3,Why do transformers use multi-head attention i...,Multi-head attention allows the model to atten...,Transformers use multi-head attention instead ...,ERROR: Error code: 429 - {'error': {'message':...,0.472222,0.142857,0.250000,0.120482,0.000000,0.072289
4,What components are included in a standard tra...,A transformer block includes a multi-head self...,A standard transformer block consists of a res...,ERROR: Error code: 429 - {'error': {'message':...,0.447761,0.215385,0.388060,0.000000,0.000000,0.000000

In [ ]:
summary = pd.DataFrame([
    {
        "Method": "Naive RAG",
        "ROUGE-1": df_results["naive_rouge1"].mean(),
        "ROUGE-2": df_results["naive_rouge2"].mean(),
        "ROUGE-L": df_results["naive_rougeL"].mean(),
    },
    {
        "Method": "Contextual Retrieval",
        "ROUGE-1": df_results["contextual_rouge1"].mean(),
        "ROUGE-2": df_results["contextual_rouge2"].mean(),
        "ROUGE-L": df_results["contextual_rougeL"].mean(),
    }
])

summary

                 Method   ROUGE-1   ROUGE-2   ROUGE-L
0             Naive RAG  0.394312  0.141468  0.288752
1  Contextual Retrieval  0.110405  0.020516  0.085793

In [ ]:
summary_rounded = summary.copy()
summary_rounded["ROUGE-1"] = summary_rounded["ROUGE-1"].round(4)
summary_rounded["ROUGE-2"] = summary_rounded["ROUGE-2"].round(4)
summary_rounded["ROUGE-L"] = summary_rounded["ROUGE-L"].round(4)

summary_rounded

                 Method  ROUGE-1  ROUGE-2  ROUGE-L
0             Naive RAG   0.3943   0.1415   0.2888
1  Contextual Retrieval   0.1104   0.0205   0.0858

In [ ]:
df_results.to_csv("answer/rouge_detailed_results.csv", index=False)
summary_rounded.to_csv("answer/rouge_summary.csv", index=False)

print("Saved ROUGE detailed results and summary.")

Saved ROUGE detailed results and summary.

Sav Broken API answer

In [ ]:
failed_rows = []

for i, item in enumerate(qa_pairs):
    ans = item.get("contextual_retrieval_answer", "")
    
    if "ERROR" in ans or ans.strip() == "":
        failed_rows.append(i)

print("Failed rows:", len(failed_rows))
print(failed_rows[:10])

In [59]:
print("hello")

hello